### ISSUE TITLE
schema 2011-06 failing to parse

### ISSUE THREAD

**Issue by toloudis** [tlambert03/ome-types#88]
The attached ome xml fails to parse in ome-types.
Here's the error I get:
```
Traceback (most recent call last):
  File "scratch.py", line 7, in <module>
    ome_obj = from_xml("./test_ome.xml")
  File "/Users/danielt/opt/anaconda3/envs/scratch/lib/python3.8/site-packages/ome_types/__init__.py", line 37, in from_xml
    d = to_dict(xml)
  File "/Users/danielt/opt/anaconda3/envs/scratch/lib/python3.8/site-packages/ome_types/schema.py", line 254, in to_dict
    schema = schema or get_schema(xml)
  File "/Users/danielt/opt/anaconda3/envs/scratch/lib/python3.8/site-packages/ome_types/schema.py", line 71, in get_schema
    return _build_schema(resource.namespace)
  File "/Users/danielt/opt/anaconda3/envs/scratch/lib/python3.8/site-packages/ome_types/schema.py", line 48, in _build_schema
    schema = xmlschema.XMLSchema(namespace)
  File "/Users/danielt/opt/anaconda3/envs/scratch/lib/python3.8/site-packages/xmlschema/validators/schema.py", line 429, in __init__
    self.parse_error(e.reason, elem=e.elem)
  File "/Users/danielt/opt/anaconda3/envs/scratch/lib/python3.8/site-packages/xmlschema/validators/xsdbase.py", line 169, in parse_error
    raise error
xmlschema.validators.exceptions.XMLSchemaParseError: <Element '{http://www.w3.org/1999/xhtml}html' at 0x7fed78517a90> is not an element of the schema:

Schema:

  <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
          <title>Open Microscopy Environment OME Schema</title>
  </head>
  <body>
  <h1>Open Microscopy Environment OME Schema</h1>
  <div class="head">
  <p>June 2011</p>
  </div>
  <div id="toc">
  <h2>Table of contents</h2>
          <ol>
                  <li><a href="#intro">Introduction</a></li>
                  <li><a href="#status">Status</a></li>
                  <li><a href="#schema">Schema</a></li>
          </ol>
  </div>
  <div id="intro">
  <h2>Introduction</h2>
  <p>This document outlines the OME Schema created by the
  ...
  ...
  </html>

Path: /html
```

[test_ome.xml.zip](https://github.com/tlambert03/ome-types/files/6468711/test_ome.xml.zip)

**Comment by toloudis** [comment]
It looks like it is somehow reading the html document at http://www.openmicroscopy.org/Schemas/OME/2011-06 instead of the true xsd file?

**Comment by joshmoore** [comment]
@tloudis: the xsi:schemaLocation at least matches those in https://downloads.openmicroscopy.org/images/OME-XML/2011-06/z-series.ome.xml

**Comment by joshmoore** [comment]
Also looks like there are several enum issues:
 * 'Spinning Disk Confocal' not a supported value of 'class ome.xml.model.enums.AcquisitionMode'
 * 'Alternate source' not a supported value of 'class ome.xml.model.enums.IlluminationType'

If I replace those with "Other" then bfconvert will gladly create a black image from the XML.

<details><summary>output</summary>

```
(base) /tmp $bfconvert test_ome.xml test.ome.tif
test_ome.xml
OMEXMLReader initializing test_ome.xml
Populating metadata
Exception in thread "main" loci.formats.FormatException: loci.common.services.ServiceException: ome.xml.model.enums.EnumerationException: 'Alternate source' not a supported value of 'class ome.xml.model.enums.IlluminationType'
	at loci.formats.in.OMEXMLReader.initFile(OMEXMLReader.java:267)
	at loci.formats.FormatReader.setId(FormatReader.java:1421)
	at loci.formats.ImageReader.setId(ImageReader.java:849)
	at loci.formats.tools.ImageConverter.testConvert(ImageConverter.java:506)
	at loci.formats.tools.ImageConverter.main(ImageConverter.java:1095)
Caused by: loci.common.services.ServiceException: ome.xml.model.enums.EnumerationException: 'Alternate source' not a supported value of 'class ome.xml.model.enums.IlluminationType'
	at loci.formats.services.OMEXMLServiceImpl.createRoot(OMEXMLServiceImpl.java:417)
	at loci.formats.services.OMEXMLServiceImpl.createOMEXMLMetadata(OMEXMLServiceImpl.java:373)
	at loci.formats.services.OMEXMLServiceImpl.createOMEXMLMetadata(OMEXMLServiceImpl.java:360)
	at loci.formats.in.OMEXMLReader.initFile(OMEXMLReader.java:261)
	... 4 more
Caused by: ome.xml.model.enums.EnumerationException: 'Alternate source' not a supported value of 'class ome.xml.model.enums.IlluminationType'
	at ome.xml.model.enums.IlluminationType.fromString(IlluminationType.java:101)
	at ome.xml.model.Channel.update(Channel.java:240)
	at ome.xml.model.Channel.<init>(Channel.java:164)
	at ome.xml.model.Pixels.update(Pixels.java:367)
	at ome.xml.model.Pixels.<init>(Pixels.java:167)
	at ome.xml.model.Image.update(Image.java:357)
	at ome.xml.model.Image.<init>(Image.java:161)
	at ome.xml.model.OME.update(OME.java:314)
	at ome.xml.model.OME.<init>(OME.java:155)
	at ome.xml.meta.OMEXMLMetadataRoot.<init>(OMEXMLMetadataRoot.java:68)
	at loci.formats.services.OMEXMLServiceImpl.createRoot(OMEXMLServiceImpl.java:412)
	... 7 more
(base) /tmp $vi test_ome.xml
(base) /tmp $bfconvert test_ome.xml test.ome.tif
test_ome.xml
OMEXMLReader initializing test_ome.xml
Populating metadata
[OME-XML] -> test.ome.tif [OME-TIFF]
	Converted 14/300 planes (4%)
	Converted 46/300 planes (15%)
	Converted 77/300 planes (25%)
	Converted 107/300 planes (35%)
	Converted 138/300 planes (46%)
	Converted 169/300 planes (56%)
	Converted 200/300 planes (66%)
	Converted 231/300 planes (77%)
	Converted 261/300 planes (87%)
	Converted 292/300 planes (97%)
	Converted 300/300 planes (100%)
[done]
11.949s elapsed (0.53333336+34.21ms per plane, 1250ms overhead)
```

</details>

**Comment by toloudis** [comment]
Yep, I can reproduce the "real" errors using bftools xmlvalid but we need to do this through a python codepath and so need to get past that weird schema error.   If bftools xmlvalid can work , then maybe something is really wrong on the python xmlschema side.(?)
The real intent here is : 
We have some old data that we want to clean up and make sure is valid.  We kind of know it's invalid and so want to write python scripts to clean it up.  Using aicsimageio and ome-types.  But there might be a reasonable code path via just manipulating the xml directly before trying to parse/validate it.

**Comment by joshmoore** [comment]
I see XSLT in your future to clean it up ;) Ok. I don't have and leads on xmlschemas handling. I'll leave you in @tlambert03's capable hands and go to sleep.

**Comment by tlambert03** [comment]
thank you both for the helpful thread!  pretty busy today and tomorrow but will try to look asap.

**Comment by tlambert03** [comment]
Hi @toloudis, sorry for the delay here.

I don't have a lot of bandwidth to extend support to older schema (we made a decision a little while ago to focus on 2016 for now), but at first glance it looks like we'd need to solve two problems here:

1. first, as commented by @joshmoore in https://github.com/tlambert03/ome-types/issues/88#issuecomment-840058515, the xml file doesn't seem to be fully valid, and it doesn't validate with `xmlschema` directly, that part will need to be on your end:
```python
In [1]: from xmlschema import validate
In [2]: validate('/Users/talley/Downloads/test_ome.xml')
XMLSchemaValidationError: failed validating 'Spinning Disk Confocal' with XsdEnumerationFacets("['WideField', 'LaserScanningConfocalMicroscopy', 'SpinningDiskConfocal', 'SlitScanConfocal', 'MultiPhotonMicroscopy', ...]"):
```

2. The incorrect fetching of the schema from the URL is a bug on our end and something I can fix soon

**Comment by toloudis** [comment]
Thanks.  Number 2 is the only thing I am worried about and is the real issue I am reporting here.

**Comment by tlambert03** [comment]
Thanks, number 2 is an easy fix...  I'm more worried about how a valid  2011 schema will be handled here.  But if ome provides a converter, we could run that on it first. 

For a while, I was making this in a schema agnostic way, but there were far too many special case things to handle so we just decided to focus on 2016.  Once you have a valid 2011 file, feel free to link it here, would be curious to see what happens with it

**Comment by toloudis** [comment]
What I did instead was do a bunch of string and element manipulations to make it validate against 2016 :)
If we come up with some 2011 data that is valid, I'll give it a try and report here.

**Comment by tlambert03** [comment]
Awesome.  Thanks!

**Comment by tlambert03** [comment]
part 2 solved in #92...  do you want to keep this open until we figure out the 2011 support?  or treat that seperately

**Comment by toloudis** [comment]
I think it's fine if it loads the schema that the xml says to load, and validates against that.  If I get ordinary validation errors then I'm in good shape.  

I totally accept that the actual object model is intended to be the most current schema.

**Comment by tlambert03** [comment]
ok.  merged it!  let me know if/when you run into the next hurdle :)
